// ─── Platform ────────────────────────────────────────────────────────────────

export type Platform = 'web' | 'mobile' | 'desktop';

// ─── Test Step (generated by AI) ─────────────────────────────────────────────

export type StepAction =
  | 'navigate'
  | 'click'
  | 'fill'
  | 'press'
  | 'select'
  | 'hover'
  | 'scroll'
  | 'wait'
  | 'assert_text'
  | 'assert_visible'
  | 'assert_url'
  | 'assert_title'
  | 'assert' // New consolidated assertion type
  | 'screenshot';

export interface TestStep {
  action: StepAction;
  /** CSS selector, role, label, or complex target object { primary, fallback } */
  target?: string | { primary: string; fallback: string[] };
  /** Value to type, URL to navigate to, or text to assert */
  value?: string;
  /** Human-readable description shown in reports */
  description: string;
  /** Intent metadata for AI and debugging (e.g., 'login_submit') */
  intent?: string;
  /** Step-specific timeout override in Ms */
  timeout?: number;
  /** Step-specific retry count override */
  retries?: number;
  /** If true, the test continues even if this step fails */
  optional?: boolean;
  /** Frame context if the element is inside an iframe (e.g., 'frame_0' or '#stripe-frame') */
  frame?: string;
  /** Sub-type for 'assert' action: 'visible' | 'text' | 'url' */
  assertType?: 'visible' | 'text' | 'url';
}

// ─── Generated Test Plan ──────────────────────────────────────────────────────

export interface TestPlan {
  /** Short title summarising what is being tested */
  title: string;
  platform: Platform;
  /** The original natural language instruction */
  naturalLanguageInput: string;
  steps: TestStep[];
  /** Schema version for backward compatibility */
  version?: number;
}

// ─── Step Result ─────────────────────────────────────────────────────────────

export interface StepResult {
  step: TestStep;
  status: 'passed' | 'failed' | 'skipped' | 'blocked';
  durationMs: number;
  error?: string;
  reason?: string;
  message?: string;
  /** File path to screenshot, if captured */
  screenshotPath?: string;
  /** Captured network errors during this step (status >= 400) */
  networkErrors?: Array<{ url: string; status: number; statusText: string }>;
  /** Selection trace for debugging (which strategy was used) */
  selectionTrace?: string;
}

// ─── Test Result ─────────────────────────────────────────────────────────────

export interface TestResult {
  id?: string;
  plan: TestPlan;
  status: 'passed' | 'failed' | 'error';
  stepResults: StepResult[];
  totalDurationMs: number;
  startedAt: string;
  /** File path to the HTML report */
  reportPath?: string;
  /** Top-level error if setup/teardown failed */
  error?: string;
}

// ─── Driver Interface ─────────────────────────────────────────────────────────

export interface Driver {
  /** Launch the browser / app / device */
  launch(target: string): Promise<void>;
  /** Execute a single step and return its result */
  executeStep(step: TestStep): Promise<StepResult>;
  /** Tear down cleanly */
  close(): Promise<void>;
}

// ─── CLI Options ──────────────────────────────────────────────────────────────

export interface CLIOptions {
  platform: Platform;
  /** URL for web, app bundle id for mobile, exe path for desktop */
  url: string;
  /** Natural language test description */
  test: string;
  /** Anthropic API key (falls back to ANTHROPIC_API_KEY env var) */
  apiKey?: string;
  /** Output directory for reports */
  output?: string;
  /** Run browser in headless mode */
  headless?: boolean;
}

// ─── Site Audit ──────────────────────────────────────────────────────────────

export type AuditPersona = 'screen-reader' | 'low-vision' | 'keyboard-only' | 'color-blind' | 'all';

export interface AuditIssue {
  type: 'error' | 'warning' | 'info';
  message: string;
  url?: string;
  location?: string;
  severity: 'critical' | 'high' | 'moderate' | 'low';
  impact?: string;
  recommendation?: string;
  selector?: string;
  confidence?: 'high' | 'medium' | 'low';
  deduction?: number; // Optional tracking of score impact
  // Enhanced Accessibility Fields
  category?: string;
  helpUrl?: string;
  fix?: string;
  screenshotPath?: string;
}

export interface AuditCategory {
  score: number;
  status: 'passed' | 'failed' | 'warning';
  issues: AuditIssue[];
  metrics?: Record<string, string | number>;
}

export interface AuditResult {
  id?: string;
  url: string;
  timestamp: string;
  categories: {
    functional: AuditCategory;
    ui: AuditCategory;
    links: AuditCategory;
    console: AuditCategory;
    performance: AuditCategory;
    accessibility?: AuditCategory;
    seo?: AuditCategory;
  };
  totalScore: number;
  reportPath?: string;
  // Device Emulation Support
  profile?: string;
  comparisons?: Record<string, AuditResult>;
}
