import React from 'react';
import Footer from './Footer';

const AboutPage: React.FC<{ onSwitchTab: (tab: string) => void }> = ({ onSwitchTab }) => {
  const theme = {
    bg: '#0B0F0C',
    surface: '#121814',
    border: '#1F2922',
    accent: '#c8f069',
    text: '#ffffff',
    textMuted: '#9CA3AF',
    glass: 'rgba(255, 255, 255, 0.03)',
  };

  const stats = [
    { label: 'Tests Run', value: '12M+' },
    { label: 'Bugs Caught', value: '850K+' },
    { label: 'Developers', value: '50K+' },
    { label: 'Uptime', value: '99.99%' },
  ];

  const values = [
    { title: 'Quality First', desc: 'We believe that quality is not a luxury, it is a necessity for every shipping team.', icon: '🎯' },
    { title: 'AI for Humans', desc: 'Our AI is built to augment developers, not replace them. We focus on developer experience.', icon: '🤖' },
    { title: 'Speed constant', desc: 'In a world of fast shipping, testing should never be the bottleneck.', icon: '⚡' },
  ];

  return (
    <div style={{ background: theme.bg, color: theme.text, minHeight: '100vh', padding: '120px 24px 0', fontFamily: 'var(--font-sans)', position: 'relative', overflow: 'hidden' }}>
      {/* Decorative Glows */}
      <div style={{ position: 'absolute', top: -100, right: -100, width: 600, height: 600, background: 'radial-gradient(circle, rgba(200, 240, 105, 0.05) 0%, transparent 70%)', zIndex: 0 }} />

      <div style={{ maxWidth: 1000, margin: '0 auto', position: 'relative', zIndex: 1 }}>
        {/* HERO */}
        <section style={{ textAlign: 'center', marginBottom: 120, animation: 'fadeUp 0.8s ease-out' }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '6px 16px', borderRadius: 100, border: `1px solid ${theme.border}`, background: theme.glass, color: theme.accent, fontSize: 13, fontWeight: 700, marginBottom: 24 }}>
            🌍 Our Mission
          </div>
          <h1 style={{ fontSize: 'clamp(40px, 8vw, 72px)', fontWeight: 800, lineHeight: 1.1, letterSpacing: '-0.03em', marginBottom: 32 }}>
            Engineering the future of <span style={{ color: theme.accent }}>Software Trust.</span>
          </h1>
          <p style={{ fontSize: 20, color: theme.textMuted, lineHeight: 1.6, maxWidth: 700, margin: '0 auto' }}>
            TestPilot AI was born out of a simple frustration: testing is too slow for the modern web. We're on a mission to automate the tedious parts of QA so engineers can focus on building.
          </p>
        </section>

        {/* STATS */}
        <section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 24, marginBottom: 120 }}>
          {stats.map((stat, i) => (
            <div key={i} style={{ 
              padding: '32px', 
              background: theme.surface, 
              border: `1px solid ${theme.border}`, 
              borderRadius: 24, 
              textAlign: 'center',
              animation: `fadeUp 0.8s ease-out ${i * 0.1}s forwards`,
              opacity: 0
            }}>
              <div style={{ fontSize: 40, fontWeight: 800, color: theme.accent, marginBottom: 8 }}>{stat.value}</div>
              <div style={{ fontSize: 14, fontWeight: 700, color: theme.textMuted, letterSpacing: 1 }}>{stat.label.toUpperCase()}</div>
            </div>
          ))}
        </section>

        {/* CONTENT SPLIT */}
        <section style={{ display: 'flex', gap: 80, alignItems: 'center', marginBottom: 160 }} className="mobile-col">
          <div style={{ flex: 1 }}>
            <h2 style={{ fontSize: 36, fontWeight: 700, marginBottom: 24 }}>Automation with Empathy</h2>
            <p style={{ fontSize: 18, color: theme.textMuted, lineHeight: 1.7, marginBottom: 24 }}>
              We don't believe in "black box" AI. Every test generated by TestPilot is editable, readable, and ownable by your team. We provide the scaffolding, you provide the intent.
            </p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              {['Auto-repairing selectors', 'Cross-browser consistency', 'Deep accessibility auditing'].map((feature, i) => (
                <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                  <div style={{ width: 20, height: 20, borderRadius: '50%', background: 'rgba(200, 240, 105, 0.1)', color: theme.accent, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 12 }}>✓</div>
                  <span style={{ fontWeight: 600 }}>{feature}</span>
                </div>
              ))}
            </div>
          </div>
          <div style={{ flex: 1, position: 'relative' }}>
            <div style={{ width: '100%', aspectRatio: '1/1', background: theme.surface, borderRadius: 32, border: `1px solid ${theme.border}`, overflow: 'hidden', position: 'relative' }}>
              <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(45deg, rgba(200, 240, 105, 0.05), transparent)' }} />
              <div style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', fontSize: 80 }}>🛸</div>
            </div>
          </div>
        </section>

        {/* CORE VALUES */}
        <section style={{ marginBottom: 120 }}>
          <h2 style={{ fontSize: 32, fontWeight: 800, textAlign: 'center', marginBottom: 60 }}>How we work</h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 32 }}>
            {values.map((v, i) => (
              <div key={i} style={{ padding: 40, background: theme.surface, border: `1px solid ${theme.border}`, borderRadius: 28, transition: 'all 0.3s' }} className="value-card">
                <div style={{ fontSize: 32, marginBottom: 24 }}>{v.icon}</div>
                <h3 style={{ fontSize: 22, fontWeight: 700, marginBottom: 16 }}>{v.title}</h3>
                <p style={{ color: theme.textMuted, lineHeight: 1.6 }}>{v.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* CTA */}
        <section style={{ 
          padding: '80px', 
          background: `linear-gradient(135deg, ${theme.surface} 0%, #000 100%)`, 
          borderRadius: 40, 
          border: `1px solid ${theme.border}`, 
          textAlign: 'center',
          position: 'relative',
          overflow: 'hidden'
        }}>
          <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 1, background: 'linear-gradient(90deg, transparent, rgba(200, 240, 105, 0.2), transparent)' }} />
          <h2 style={{ fontSize: 32, fontWeight: 700, marginBottom: 24 }}>Join our pilot program</h2>
          <p style={{ color: theme.textMuted, marginBottom: 40, maxWidth: 500, margin: '0 auto 40px' }}>Be the first to know about new features and help us shape the future of testing.</p>
          <button 
            onClick={() => onSwitchTab('contact')}
            style={{ background: theme.accent, color: '#000', border: 'none', padding: '16px 40px', borderRadius: 100, fontSize: 16, fontWeight: 700, cursor: 'pointer' }}
          >
            Contact the Team
          </button>
        </section>
      </div>

      <Footer onSwitchTab={onSwitchTab} />

      <style>{`
        @keyframes fadeUp {
          from { opacity: 0; transform: translateY(20px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .value-card:hover {
          transform: translateY(-8px);
          border-color: rgba(200, 240, 105, 0.3);
          box-shadow: 0 20px 40px rgba(0,0,0,0.4);
        }
        @media (max-width: 768px) {
          .mobile-col { flex-direction: column !important; gap: 40px !important; }
        }
      `}</style>
    </div>
  );
};

export default AboutPage;
